apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-rc

spec:
  template:
    metadata:
      name: my-app
      labels:
        env: production
    spec:
      containers:
      - name: nginx
        image: nginx

  replicas: 3
